global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kestra'
    static_configs:
      - targets: ['kestra:8080']
    metrics_path: '/metrics'

  - job_name: 'superset'
    static_configs:
      - targets: ['superset:8088']
    metrics_path: '/metrics'

  - job_name: 'pivot'
    static_configs:
      - targets: ['pivot:8080']
    metrics_path: '/metrics'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 